const emotionMessages = [
    "Ready to make your move? Choose wisely!",
    "Rock, paper, or scissors? What’s your first bet?",
    "The stakes are high! What’s your next choice?",
    "Feeling lucky? Try a bold move!",
    "Anticipation builds as the items collide!",
    "Stay sharp! Your next move could be the game-changer.",
    "Think ahead! What's your strategy?",
    "The tension rises with each clash on the field!",
    "What’s your gut telling you? Go with it!",
    "Every round is a new opportunity. What’s your next step?",
    "Will you stick with your choice or switch it up?",
    "Your intuition is your strongest ally. Trust it!",
    "The crowd is watching! What will you choose?",
    "The game is heating up! Keep your cool.",
    "What’s your secret weapon this round?",
    "Analyze the field and make your move!",
    "Your decision could lead to victory or defeat!",
    "Can you predict your opponent’s next move?",
    "Stay focused! The battle is just beginning.",
    "Excitement builds as the next round begins!",
    "Stay unpredictable! Keep them guessing.",
    "What’s your strategy to outsmart the opponent?",
    "The pressure is on! Make it count.",
    "Feeling confident? Take the challenge head-on!",
    "What’s the best way to counter their last move?",
    "The game's dynamics are changing! Adapt quickly.",
    "Anticipation is key. What’s your next play?",
    "Consider the odds and make your choice.",
    "What will you wager this time?",
    "The energy is electric! How will you play?",
    "Stay on your toes! The game is constantly shifting.",
    "A smart move now could secure your victory later.",
    "Think like your opponent. What will they do?",
    "The thrill of the game is in the unpredictability!",
    "Your next decision could make or break the game!",
    "Stay resilient! Every round is a new battle.",
    "The stakes rise with every passing moment!",
    "What’s your plan to seize the advantage?",
    "The field is set! Time to make your move.",
    "Keep your strategy flexible and your mind open.",
    "What’s your next bold move?",
    "The tension is palpable! What’s your next play?",
    "Every choice matters in this high-stakes game.",
    "What’s your secret to staying ahead?",
    "The arena awaits your decision!",
    "Stay calm under pressure. It’s your move.",
    "Every player has a strategy. What’s yours?",
    "The thrill of the game keeps everyone on edge!",
    "What’s your instinct telling you?",
    "Strategy is key! How will you outplay them?",
    "Trust your instincts and make the call.",
    "Stay alert! The game is always changing.",
    "The next move is critical. Choose wisely.",
    "Every bet counts! How will you proceed?",
    "The excitement is building with each round!",
    "How will you turn the tide in your favor?",
    "Stay unpredictable and keep them on their toes!",
    "What’s your plan for the next encounter?",
    "The battlefield is set. Time to act!",
    "Stay composed and think strategically.",
    "What’s your next strategic maneuver?",
    "The game’s intensity is rising! Be ready.",
    "What will you do to outwit your opponent?",
    "Stay focused and make every move count.",
    "The arena is alive with anticipation!",
    "Think ahead and plan your next steps carefully.",
    "What’s your strategy to gain the upper hand?",
    "The thrill of the game is in the unexpected!",
    "Stay calm and calculated. It’s your move.",
    "Every choice could lead to victory or defeat!",
    "What’s your secret to maintaining composure?",
    "The game’s dynamics are ever-changing!",
    "Stay sharp and make your next move!",
    "Keep your strategy agile and adaptable.",
    "What’s your plan to turn the tables?",
    "The stakes are high! Make your move count.",
    "The game is a test of wits and nerves!",
    "Stay focused on the prize! What's your play?",
    "What’s your strategy for the next round?",
    "The tension is mounting as the game progresses!",
    "Stay ahead of the game with your next move.",
    "Each round is a new opportunity to win!",
    "What’s your game plan for the next phase?",
    "The game is a battle of minds and strategies!",
    "Stay vigilant and make your next move wisely.",
    "The excitement is palpable as the game unfolds!",
    "What’s your next strategic decision?",
    "Stay sharp and ready for anything!",
    "The game is an ever-evolving challenge!",
    "What’s your approach for the upcoming round?",
    "The arena is charged with energy and anticipation!",
    "Stay alert and anticipate your opponent’s moves.",
    "What’s your plan to stay one step ahead?",
    "The thrill of competition fuels the game!",
    "Stay calm and collected as you make your move.",
    "Every decision is a step towards victory or defeat!",
    "What’s your tactic to claim the upper hand?",
    "The game’s tempo is quickening! Be prepared.",
    "Stay strategic and make your presence known.",
    "What’s your next move to secure your lead?",
    "The intensity of the game is unmatched!",
    "Stay engaged and make every move count.",
    "What’s your secret weapon in this round?",
];

function generateEmotionResponse() {
    return emotionMessages[Math.floor(Math.random() * emotionMessages.length)];
}

const touchMessages = [
    "Hey there! Ready to play? Let's see what your fingers can do!",
    "Tap, tap! Your next move is just a touch away. Choose wisely!",
    "I'm counting on your touch to bring us victory! What will it be?",
    "Your touch is magic! Let's see what you conjure up next!",
    "A gentle tap could lead to a big win! What’s your move?",
    "Ready to wiggle those fingers? The game awaits your touch!",
    "Your touch has a special power! Show me your next move.",
    "Touch the screen and let the magic unfold! What’s your choice?",
    "Your fingers hold the key to victory. Ready to make your move?",
    "I’m here cheering for you! Give the screen a little tap for good luck!"
];

function generateTouchResponse() {
    return touchMessages[Math.floor(Math.random() * touchMessages.length)];
}


module.exports = {generateEmotionResponse, generateTouchResponse};
